### ISSUE TITLE
Animação para o menu

### ISSUE THREAD

**Issue by guilhermeluciosilva** [Print-TesteServer/Desenvolvendo-meu-primeiro-Jogo-Mundo-Bit-#1]
Adorei a ideia, posso fazer um vídeo "animação" para usar no seu menu? achei ele muito estático e séria legal ter um vídeo do jogo passando atras. Mas um vídeo vai te ajudar? que tipo de extensão o pygames usa para isso? é que não conheço essa biblioteca. 

Minha ideia é cruzar essas duas imagens e dar movimento para a do jogo:
![menu](https://user-images.githubusercontent.com/61800391/84964545-c4daea00-b0e2-11ea-86e0-47f9d15a8335.png)
![Jogo0 1](https://user-images.githubusercontent.com/61800391/84964549-c73d4400-b0e2-11ea-991c-1d376dfd0c9f.png)

**Comment by Print-TesteServer** [comment]
@guilhermeluciosilva , obrigado, fico feliz que tenha gostado, sim eu também achei bem estático o menu, a ideia é boa mas ainda não cheguei a ver como fazer...rsrs
 ## Extensões que uso:
- Python 3.7
- pygame 1.9.6
- pygame_gui 0.5.6

## OBS
Aparentemente é necessário usar mais 1 biblioteca para produzir um vídeo... @pyglet, ainda estou vendo como fazer...

**Comment by guilhermeluciosilva** [comment]
Posso criar um mp4 para você? acha que consegue colocar no menu?

**Comment by Print-TesteServer** [comment]
# Pode criar sim!
  Agradeço, talvez demore para conseguir colocar... mas uma hora vai! :rocket:

**Comment by guilhermeluciosilva** [comment]
Hey, eu baixei a foto do terreno mas ficou em baixa resolução, teria outra para eu baixar?

**Comment by Print-TesteServer** [comment]
Opa, deve ser por conta do tamanho, que foi feita em pixel art, consigo converter o tamanho no programa aqui, qual tamanho Ta bom para Você?

(Obs: ignora isso de abrir e fechar a issue... acabei clicando errado no app do Github.)

**Comment by guilhermeluciosilva** [comment]
Consegue deixar do tamanho das que eu mandei no inicio do tópico? rs (não sei quantos px hehehe)

**Comment by guilhermeluciosilva** [comment]
Não só o terreno e uma imagem dos inimigos

**Comment by Print-TesteServer** [comment]
# Boa noite
Então... tive um problema com meu teclado, e acho q vou ficar sem por um tempinho... Se puder, pega essas imagens, abre o **Piskel** no navegador, arrasta elas 1 de cada vez nele, e clica para exportar, ae você pode escolher o tamanho, se não puder teremos que aguardar eu arrumar aqui.

**Comment by guilhermeluciosilva** [comment]
Vou fazer ^^ se der certo te aviso! Vlww
